-- CREATE DATABASE IF NOT EXISTS socialv2_db;
--
-- CREATE TABLE IF NOT EXISTS users (
--                                      id BIGSERIAL PRIMARY KEY,
--                                      name VARCHAR(255) NOT NULL,
--                                      email VARCHAR(255) UNIQUE NOT NULL,
--                                      password TEXT NOT NULL,
--                                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- CREATE TABLE IF NOT EXISTS posts (
--                                      id BIGSERIAL PRIMARY KEY,
--                                      title VARCHAR(255) NOT NULL,
--                                      content TEXT NOT NULL,
--                                      tags TEXT[] DEFAULT '{}',
--                                      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
--                                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
